### ISSUE TITLE
Windows UI Error

### ISSUE THREAD

**Issue by dschultz-01** [liyuanhe211/Energy_Diagram_Plotter_CDXML#3]
I installed this on a windows machine. I double click the .bat file, but the UI doesn't show up properly (see pic below). Is this an error in the .bat? If so, is there a straightforward way to address this?

![energy_diagram_windows_issue](https://user-images.githubusercontent.com/111896146/186203339-fabf35e6-31e1-43d4-b759-75950683b080.png)

**Comment by dschultz-01** [comment]
Additionally, I attempted to use the Draw_Energy_Diagram_XML.exe application instead, but it crashes instantly with no reported errors.

**Comment by liyuanhe211** [comment]
> I installed this on a windows machine. I double click the .bat file, but the UI doesn't show up properly (see pic below). Is this an error in the .bat? If so, is there a straightforward way to address this?
> 
> ![energy_diagram_windows_issue](https://user-images.githubusercontent.com/111896146/186203339-fabf35e6-31e1-43d4-b759-75950683b080.png)

The error in the cmd window is irrelevant to your problem.
This is a high-DPI support issue caused by the PyQt module. At this time, I'm not exactly sure what's the foolproof way to deal with all possible DPI (as I only have one screen to test on) on all platform. 

For the time being, please try this:
Open `Python_Lib\My_Lib_PyQt.py` with a text editor.
Comment out these three lines in the beginning of the file (by adding "#" in the front of each line).
```
if platform.system() == 'Windows':
    os.environ["QT_SCALE_FACTOR"] = "0.85"
    QApplication.setAttribute(Qt.Qt.AA_EnableHighDpiScaling, True)
```
And see whether it solved your problem.

I'll try to find a more permanent solution later.

**Comment by liyuanhe211** [comment]
> Additionally, I attempted to use the Draw_Energy_Diagram_XML.exe application instead, but it crashes instantly with no reported errors.

Please try to open a command line window, `cd` to the directory where `Draw_Energy_Diagram_XML.exe` lies, and run `Draw_Energy_Diagram_XML.exe` in it. The window should retain the error message. Please tell me what's the error message there.

**Comment by liyuanhe211** [comment]
I've updated the script. Please clone the new version and have a try.

**Comment by liyuanhe211** [comment]
Feedback from people previously reporting the similar issue show that the problem is solved with the last update. If you tried the new version and it's still not fixed, please create a new issue.
